### ISSUE TITLE
Authentication failed because the remote party has closed the transport stream.

### ISSUE THREAD

**Issue by AngeloAnolin** [pusher/pusher-http-dotnet#49] opened 2018-11-12 21:16 UTC
I am getting a weird issue trying to peruse the .NET library for Pusher.

Using the latest (4.1.0), and following the guidelines provided (in the Getting Started Tab for ASP.NET):

https://dashboard.pusher.com/apps/#######/getting_started

I am getting the error:
**Authentication failed because the remote party has closed the transport stream**.

I tried to peruse the old .NET package (3.0)

and in my code:
```
 var options = new PusherOptions
{
  Cluster = "us2",
  Encrypted = true
};
var pusher = new Pusher("#######", "********", "*******", options);
pusher.Trigger("channel", "event", data);
```

I am getting the error object not set to an instance of an object. Expanding the exception details does not provide any context whatsoever.

I'd appreciate some insight on the way forward to resolve this. As of now, I am already hitting a wall on what to do further to have my application code working.

**Comment by elverkilde** [comment] 2021-03-08 12:19
This was resolved through support, closing this issue.

For posterity, this was caused by a mis-configured auth endpoint. If you end up in a similar situation, we recommend reading through the documentation: https://pusher.com/docs/channels/server_api/authenticating-users

If that doesn't help, feel free to reach out to support: support@pusher.com

**Closed by elverkilde** 2021-03-08 12:19 UTC
